replicaCount: 1

image:
  repository: goplanirahul77/docker-gs-ping
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 8080

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: dockergs.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
